version: "3"
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    env_file: .env
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    build: .
    depends_on:
      - db
    networks:
      - backend
    env_file: .env

  proxy:
    image: nginx
    volumes:
      - ./website.template:/etc/nginx/conf.d/website.template
    ports:
      - "80:8080"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=8080
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/website.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend
    depends_on:
      - web

networks:
  backend:

volumes:
  db-data:
