version: "3"
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    env_file: .env
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    networks:
      - backend
    ports:
      - "5000:5000"
    env_file: .env

networks:
  backend:

volumes:
  db-data:
